# Implementación de regresión lineal por metodo de Gradiente

Recorderis

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([8,3,6])

In [ ]:
# operaciones básicas entre arreglos vectorizados
c=a*b
b=a-b
print(c)
print(b)

[ 8  6 18]
[-7 -1 -3]


In [ ]:
e=np.pi*a
print(e)
f=np.pi+a
print(f)

[3.14159265 6.28318531 9.42477796]
[4.14159265 5.14159265 6.14159265]


In [ ]:
g=np.power(f,2)
print(g)
h=np.power(a,a)
print(h)

[17.15278971 26.43597502 37.71916032]
[ 1  4 27]


In [ ]:
j=np.sum(a)
print(j)

6


In [ ]:
if a.size==b.size:
  print("igual tamaño")
else:
  print("Diferente tamaño")

igual tamaño


Ejemplo de solución de problema de regresión lineal univariada.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import time
"""
 Función de costo que el entran los dos theta X y Y
"""
def costo(theta0,theta1,x,y):
  #donde theta0 y theta1 son los parámetros a probar,
  #x y y son nparrays de la misma dimensión
  n=x.size
  #aqui podrian depurar que los tamaños de los arreglos sean iguales

  #calculo del costo en la variable J
  J=(1/(2*n))*np.sum(np.power(( (theta0+theta1*x)-(y) ),2)) #terminen ustedes... 
  time.sleep(1)
  return J



