<a href="https://colab.research.google.com/github/gomezan/inteligencia-artificial/blob/main/Multiclase_ejemplo_ovA_ovo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression #https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
from sklearn.multiclass import OneVsOneClassifier # https://scikit-learn.org/stable/modules/generated/sklearn.multiclass.OneVsOneClassifier.html
X, y = load_iris(return_X_y=True)
import numpy as np
print("X=",X)
print("y=",y)


X= [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1

In [ ]:
clf = LogisticRegression(random_state=0,solver = 'liblinear',tol=0.00001,multi_class='ovr',max_iter=100)
clf.fit(X, y)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2', random_state=0,
                   solver='liblinear', tol=1e-05, verbose=0, warm_start=False)

In [ ]:
print("A la entrada x= \n",X[[4,50,120,121], :]," \nLa salida:  \n",clf.predict(X[[4,50,120,121], :]),"\n")
print("El vector de hipotesis de X es: ", clf.predict_proba(X[[4,50,120,121], :]),"\n")
print("accuracy: ",clf.score(X, y))# mean accuracy on the given test data and labels
proba=clf.predict_proba(X[[4,50,120,121], :])
sumadeprob=np.sum(proba,axis=1)
print("suma:",sumadeprob)


A la entrada x= 
 [[5.  3.6 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]]  
La salida:  
 [0 1 2 2] 

El vector de hipotesis de X es:  [[8.96031508e-01 1.03957293e-01 1.11992458e-05]
 [2.96027389e-02 8.61256767e-01 1.09140494e-01]
 [5.08105753e-04 2.23879926e-01 7.75611969e-01]
 [1.35045692e-03 2.28517707e-01 7.70131836e-01]] 

accuracy:  0.96
suma: [1. 1. 1. 1.]


In [ ]:
prob=clf.predict_proba(X[[4,50,120], :])
print(prob)
type(prob)
print(prob.shape)
probtotal=np.sum(prob,axis=1)
print(probtotal)


[[8.96031508e-01 1.03957293e-01 1.11992458e-05]
 [2.96027389e-02 8.61256767e-01 1.09140494e-01]
 [5.08105753e-04 2.23879926e-01 7.75611969e-01]]
(3, 3)
[1. 1. 1.]


In [ ]:
ovo=OneVsOneClassifier(LogisticRegression(random_state=0))
ovo.fit(X, y)

OneVsOneClassifier(estimator=LogisticRegression(C=1.0, class_weight=None,
                                                dual=False, fit_intercept=True,
                                                intercept_scaling=1,
                                                l1_ratio=None, max_iter=100,
                                                multi_class='auto', n_jobs=None,
                                                penalty='l2', random_state=0,
                                                solver='lbfgs', tol=0.0001,
                                                verbose=0, warm_start=False),
                   n_jobs=None)

In [ ]:
print("A la entrada x= \n",X[[4,50,120], :]," \nLa salida:  \n",ovo.predict(X[[4,50,120], :]),"\n")
#print("El vector de hipotesis de X es: ", ovo.predict_proba(X[[4,50,120], :]),"\n")
print("accuracy: ",ovo.score(X, y))# mean accuracy on the given test data and labels

A la entrada x= 
 [[5.  3.6 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.9 3.2 5.7 2.3]]  
La salida:  
 [0 1 2] 

accuracy:  0.9733333333333334
